<a href="https://colab.research.google.com/github/TsIrDrPrakas/Numpy-Index-Selection/blob/master/NumpyIndexSelection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Index Selection**

Import Library

In [1]:
import numpy as np

# **Example 1**

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Select a single valuue

In [4]:
arr[8]

8

Selecting Examples

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

Braodacsting Value

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[:5]=100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# **Example 2**

In [15]:
arr = np.arange(0,11)

# Extracting a slice of the array 'arr' from index 0 to 4 (inclusive), creating 'slice_of_arr'.


In [16]:
slice_of_arr = arr[0:5]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Assigning the value 99 to all elements in the slice 'slice_of_arr'.


In [19]:
slice_of_arr [:] = 99

In [20]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

# Creating a copy of the array 'arr' (original) and assigning it to 'arr_copy'( a copy).


In [22]:
arr_copy = arr.copy()

*Assigining New Value*

In [23]:
arr_copy [:] = 100

*Checking the Copy*

In [25]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

*Checking the Original*

In [26]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

# **Example 3**

2D Array

In [27]:
arr_2d = np.array ([[5,10,15],[20,25,30],[35,40,45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Checking the shape (row, column)

In [29]:
arr_2d.shape

(3, 3)

Selecting the 1st Row

In [30]:
arr_2d[0]

array([ 5, 10, 15])

Selecting Row 1 Column 1 = element

In [31]:
arr_2d[1,1]

25

In [32]:
arr_2d[1][1]

25

Row 1, Column 3 's Element

In [33]:
arr_2d[0,2]

15

Selecting range of Row

In [34]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

Selecting a subsection , (rows and colum)

In [35]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# **Example 3**

Conditional Selection

In [37]:
arr = np.arange (1, 11)

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
bool_arr = arr>4

In [41]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])